version: "3"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./${BACKUP_DIR}:/db_dump

  app:
    restart: unless-stopped
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=1
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - 127.0.0.1:${FLASK_PORT}:${FLASK_PORT}
    entrypoint: "bash start_server.sh"

    depends_on:
      - db

  celery_worker:
    container_name: "celery_worker"
    restart: unless-stopped
    build: .
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ADDR=redis:${REDIS_PORT}
      - BACKUP_DIR=${BACKUP_DIR}
    depends_on:
      - db
    command: >
      celery -A worker worker -B --loglevel=INFO

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    environment:
      - REDIS_PASSWORD=redis
    command: >
      --requirepass redis

volumes:
  db-data:
  db_dump:
